version: 1.0.{build}
image: Visual Studio 2019

environment:
  DOCKER_USER:
    secure: tgiachi
install:
  - docker version

build_script:
  - docker build -t tgiachi/neon:dev .

test_script:
  - docker run tgiachi:/neon

deploy_script:
  - docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
  - docker push tgiachi/neon:dev