engine:
  home_directory: C:\Neon
  use_swagger: true
  logger:
    log_level: Info
  secret_key: gS!vU@grMQ@$NhCJvsKsbDS_6uS#hhG@
  time_zone: Europe/Berlin
  unit_system: metric
  language: it
services:
  mqtt:
    client:
      hostname: test.mosquitto.org
      port: 1883
    embedded_server_port: 1883
  script_engine:
    scripts_directory:
      name: scripts
    modules_directory:
      name: modules
    write_output_on_log: true
  iot:
    entities_database:
      name: mongo_db
      connection_string: mongodb://localhost:27017/neon_iot_db
    events_database:
      name: mongo_db
      connection_string: mongodb://localhost:27017/neon_iot_db
home:
  name: My Home
  coordinate:
    latitude: 10
    longitude: 10
    elevation: 10
components:
  to_load:
  - name: sunset
  - name: weather_darksky
  - name: owntracks
  - name: sonoff_tasmoda
  - name: philip_hue
  - name: spotify
  config_directory:
    name: components
  vault_directory:
    name: vault
notifiers:
  notifier_config_directory:
    name: notifiers