engine:
  home_directory: C:\Neon
  use_swagger: true
  logger:
    log_level: Info
  secret_key: '#%hCxRCegTnes6iH6A$V69VLO#j7*b'
services:
  mqtt:
    client:
      hostname: mqtt.anaconda.net-freaks.com
      port: 1883
    embedded_server_port: 1883
  script_engine:
    directory:
      name: Scripts
