engine:
  home_directory: C:\Neon
  use_swagger: true
  logger:
    log_level: Info
  secret_key: gS!vU@grMQ@$NhCJvsKsbDS_6uS#hhG@
services:
  mqtt:
    client:
      hostname: mqtt.anaconda.net-freaks.com
      port: 1883
    embedded_server_port: 1883
  script_engine:
    scripts_directory:
      name: Scripts
    modules_directory:
      name: Modules
    write_output_on_log: true
  iot:
    entities_database:
      name: mongo_db
      connection_string: mongodb://localhost:27017/neon_iot_db
    events_database:
      name: mongo_db
      connection_string: mongodb://localhost:27017/neon_iot_db
home:
  name: My Home
  coordinate:
    latitude: 43.749690000000001
    longitude: 11.325437000000001
    elevation: 44
components:
  to_load:
  - name: weather_darksky
  - name: owntracks
  - name: sonoff_tasmoda
  - name: philip_hue
  - name: spotify
  config_directory:
    name: Components
  vault_directory:
    name: Vault
